### ISSUE TITLE
Enable rpccookiefile Support in ckpool.conf

### ISSUE THREAD

**Issue by d6n13l0l1v3r** [golden-guy/ckpool-solo#1]
Description:

To enhance security and align with best practices for bitcoind configurations, the implementation of importing/read the rpccookiefile for bitcoind is preferred over using traditional username/password authentication.

Problem:

Several tools, including corelíghthing, fulcrum, electrs, and others utilized in my Bitcoin full node, employ the rpccookiefile for enhanced security. However, there is an issue with integrating ckpool-solo into this configuration as it lacks support for the rpccookiefile.

Proposed Solution:

Enable ckpool-solo to utilize the rpccookiefile for bitcoind RPC authentication, allowing seamless integration with the security measures employed by other tools in the Bitcoin full node ecosystem.

**Comment by golden-guy** [comment]
Hi, in my opinion this is more of a convenience thing for external apps rather than added security, considering you will want the pool to run on the same machine as the bitcoind. And in fact, the cookie uses the same rpcauth mechanism, it's just auto-generated credentials on each bitcoind startup.

**Comment by golden-guy** [comment]
I have pushed some code now for the btcd cookie file auth. While I tried to cover all relevant tests, please check it out and let me know if you find anything.

**Comment by d6n13l0l1v3r** [comment]
I will do some test

**Comment by d6n13l0l1v3r** [comment]
tested and all looks fine , for me it's working as expected.

**Comment by d6n13l0l1v3r** [comment]
You are planning to create a release including this change?

**Comment by golden-guy** [comment]
Actually not, I don't think this single commit justifies a new release. Anybody who needs the cookie support can always build from HEAD.
