### ISSUE TITLE
Update ckpool-solo Repository to v0.9.9

### ISSUE THREAD

**Issue by d6n13l0l1v3r** [golden-guy/ckpool-solo#2]
Issue Description:

The current version of ckpool-solo in the repository https://bitbucket.org/ckolivas/ckpool-solo/ is v0.9.9. Please update the repository to the latest release tag, v0.9.9.

**Comment by golden-guy** [comment]
Hi, the code is actually on par with v0.9.9 and merged up to https://bitbucket.org/ckolivas/ckpool-solo/commits/114d1ad6c3572860ed077c6fcbb515fd73462eb6

**Comment by golden-guy** [comment]
Pushed the version bump to v0.9.9 as well now.
