### ISSUE TITLE
Misconfig mod on NerminerV2 branch

### ISSUE THREAD

**Issue by twofaktor** [golden-guy/ckpool-solo#5]
Hello, this config https://github.com/golden-guy/ckpool-solo/blob/nerdminer_v2/ckpool.conf with a NerdminerV2 doesn't work, if I use this config, https://github.com/golden-guy/ckpool-solo/blob/nerdminer/ckpool.conf ...yes

I think this was a missing action to modify the config file according to the Nerdminer requirement on the Nerminer_v2 branch:

```
"mindiff" : 0.000000001,
"startdiff" : 0.000000001,
```

**Comment by twofaktor** [comment]
PR opened to fix this: https://github.com/golden-guy/ckpool-solo/pull/6

**Comment by golden-guy** [comment]
Merged, so we can close this one.
